package com.wwssxx.kaiyan.module.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wwssxx.kaiyan.model.modelforvideo.WebUrl;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WEB_URL".
*/
public class WebUrlDao extends AbstractDao<WebUrl, Long> {

    public static final String TABLENAME = "WEB_URL";

    /**
     * Properties of entity WebUrl.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property KeyId = new Property(0, Long.class, "keyId", true, "_id");
        public final static Property Raw = new Property(1, String.class, "raw", false, "RAW");
        public final static Property ForWeibo = new Property(2, String.class, "forWeibo", false, "FOR_WEIBO");
    }


    public WebUrlDao(DaoConfig config) {
        super(config);
    }
    
    public WebUrlDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEB_URL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: keyId
                "\"RAW\" TEXT," + // 1: raw
                "\"FOR_WEIBO\" TEXT);"); // 2: forWeibo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEB_URL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WebUrl entity) {
        stmt.clearBindings();
 
        Long keyId = entity.getKeyId();
        if (keyId != null) {
            stmt.bindLong(1, keyId);
        }
 
        String raw = entity.getRaw();
        if (raw != null) {
            stmt.bindString(2, raw);
        }
 
        String forWeibo = entity.getForWeibo();
        if (forWeibo != null) {
            stmt.bindString(3, forWeibo);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WebUrl entity) {
        stmt.clearBindings();
 
        Long keyId = entity.getKeyId();
        if (keyId != null) {
            stmt.bindLong(1, keyId);
        }
 
        String raw = entity.getRaw();
        if (raw != null) {
            stmt.bindString(2, raw);
        }
 
        String forWeibo = entity.getForWeibo();
        if (forWeibo != null) {
            stmt.bindString(3, forWeibo);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WebUrl readEntity(Cursor cursor, int offset) {
        WebUrl entity = new WebUrl( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // keyId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // raw
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // forWeibo
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WebUrl entity, int offset) {
        entity.setKeyId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRaw(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setForWeibo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WebUrl entity, long rowId) {
        entity.setKeyId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WebUrl entity) {
        if(entity != null) {
            return entity.getKeyId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WebUrl entity) {
        return entity.getKeyId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
